## Vendra Tenant

The `misaf/vendra-tenant` package is the **generic multi-tenancy engine**. Installing it makes the application tenant-aware by binding a real `TenantResolver` over the support layer's default null resolver. Tenant is a technical role: this package owns the mechanism and never the business model that plays it — Vendra configures a `Store`, another application would configure a `Company` or `Workspace`.

### Translatable Persistence

- Making a persisted model field translatable is an explicit domain choice unless this package already requires it.
- Every field listed in a model's `$translatable` array must definitely use a JSON database column. Keep its model traits/casts, factories, validation, Filament locale UI, API serialization, and tests translation-aware.
- A field not listed in `$translatable` must use the appropriate scalar database type and must not use Spatie Translatable, translatable slug traits, locale switchers, translated callbacks, or translation-shaped array data.

### Vendra Transitive API Policy

- Treat a Vendra dependency intentionally exposed through the public API of a directly required Vendra platform package as part of the supported public contract of that package.
- Do not add a redundant direct Composer requirement solely because source code imports a type from that exposed dependency.
- Apply this only to Vendra platform packages listed under `require`; never extend it to `require-dev`, `suggest`, incidental implementation dependencies, or third-party packages. Removing or replacing an exposed dependency is a breaking change; keep `self.version` alignment across the Vendra package graph.

- Keep tenancy-engine code inside `packages/vendra-tenant` using the `Misaf\VendraTenant` namespace.
- **Tenant is a technical role, not a business entity.** This package owns no concrete tenant model. It owns `Contracts\TenantContract` (what a tenant model must be), `Contracts\HostTenantFinder` (the port that turns a host into a tenant), `Concerns\IsTenantModel`, `Support\ConfiguredTenantResolver` (binds `Misaf\VendraSupport\Contracts\TenantResolver`), `Support\NullHostTenantFinder`, the switch tasks (`SwitchAppTask`, `SwitchMailTask`), `Jobs\CacheTenantRoutesJob`, `Actions\EnableTenancyAction`, `Http\Middleware\EnsureAdminDomain`, and `TenantServiceProvider`. It is built on Spatie multitenancy.
- **Never name a business model here.** No `use Misaf\VendraStore\…`, no `Store`, no `Reseller`, no ecommerce vocabulary — not in source, config defaults, or tests. `tests/ArchTest.php` and `tests/Unit`/`Feature` assert it, and the suite is driven by a `Workspace` fixture precisely so a leak fails.
- Everything business-shaped is configuration: `vendra-tenant.model` (the class implementing `TenantContract`) and `vendra-tenant.foreign_key` (the column tenant-scoped tables carry). Read them through `TenantSchema::column()` or the resolver — never hard-code `tenant_id`. The owner relation stays `tenant()`; a business-named alias would have to live in Eloquent's process-wide relation resolvers, registered at model-boot time, so a model's API would depend on whichever config was loaded when its class first booted.
- In Vendra the configured model is `Misaf\VendraStore\Models\Store` and the foreign key stays the neutral `tenant_id`, so reusable domain packages work under any tenant model. Only Store-owned records (`store_domains`, `storefront_deployments`) use `store_id`, and they belong to `misaf/vendra-store`.
- `Jobs\CacheTenantRoutesJob` regenerates one tenant's route cache off the request lifecycle. It implements Spatie's `NotTenantAware` (it targets its tenant via `--tenant` and may be dispatched with no current tenant, e.g. from a console panel) — keep any queued job that runs across tenants `NotTenantAware`, or Spatie throws `CurrentTenantCouldNotBeDeterminedInTenantAwareJob`.
- Business availability ("may this tenant serve requests?") belongs to the concrete model, not here. `ConfiguredTenantResolver` uses an `accessible` scope when the configured model defines one and lists every tenant when it does not.
- Host resolution is a port. `EnsureAdminDomain` and the `GET /caddy/domain-check` endpoint resolve `HostTenantFinder` from the container; the application binds the adapter (Vendra binds `StoreDomainFinder` from `misaf/vendra-store`). Bind defaults with `bindIf` so provider order cannot beat the real adapter.
- The named `GET /caddy/domain-check` endpoint is only for Caddy on-demand TLS authorization. Keep it loopback-only, validate the hostname, and authorize only hosts the bound finder resolves.
- Queued notifications and jobs dispatched from host-level console or reseller flows have no current tenant. Make them implement Spatie's `NotTenantAware`; otherwise multitenancy may delete them before handling even while Horizon reports them as completed.
- No other module may depend on `misaf/vendra-tenant` except the package that supplies the concrete tenant model (`misaf/vendra-store`) and the panels above it. All other domain and API modules consume tenancy only through `misaf/vendra-support` (`TenantResolver`, `TenantAwareness`, `BelongsToTenant`). Do not create reverse dependencies.
- This applies to test suites too: module tests must not import `Misaf\VendraTenant` or declare a `misaf/vendra-tenant` dev dependency — they use the `misaf/vendra-testing` tenancy helpers (`makeCurrentTestTenant()`, `createTestTenant()`, `switchToTestTenant()`, …). The root `tests/Feature/PackageManifestConsistencyTest.php` guard enforces it.
- Keep `ConfiguredTenantResolver` a faithful implementation of the support `TenantResolver` contract; when the contract changes, update this resolver, `NullTenantResolver`, and the resolver mocks in other packages' tests together.
- `vendra-tenant:enable {tenant}` is the explicit installation-order recovery path. It consumes the support `TenantTableRegistry`, adds the configured foreign key and its index, backfills unscoped records to the selected tenant, and is safe to rerun.
- Keep per-tenant route caches because tenant route sets may diverge. Generate them with `php artisan tenants:artisan route:cache` and do not replace Spatie's `SwitchRouteCacheTask` with a project-specific subclass. Tests should remove only this task from `multitenancy.switch_tenant_tasks` instead of requiring generated cache files.
- Follow Laravel comment style: document with PHPDoc (array shapes, generics, `@see`) and reserve inline comments for genuinely complex logic.
- Keep Pest architecture tests in `tests/ArchTest.php`: the `php`, `security`, and `laravel` presets, plus the rules asserting this engine does not use `Misaf\VendraStore`, `Misaf\VendraReseller`, `Misaf\VendraConsole`, or `Misaf\VendraSubscription`.
